language: bash

services:
  - docker

env:
  global:
    - DOCKERHUB_REPO=printf

branches:
  only:
    - ci/docker-and-travis

before_install:
  - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

jobs:
  include:
    - stage: build
      script:
        - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest .

    # - stage: test
    #   script: 
    #     - docker run --rm $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest <some-test-command>

    - stage: deploy
      script:
        - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
 